### ISSUE TITLE
error when using command 'pyopmcsp11 -i csp11a.txt -o csp11a'

### ISSUE THREAD

**Issue by ReservoirSimulator** [daavid00/pyopmcsp11#7]
Hi David,

When I used pyopmcsp11, I got the error:
----------------------------------------------------------------------------
root@iZ2ze3smbnw84iffl82ycrZ:~/pyopmcsp11/examples# pyopmcsp11 -i csp11a.txt -o csp11a
Traceback (most recent call last):
  File "/usr/local/bin/pyopmcsp11", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/pyopmcsp11/core/pyopmcsp11.py", line 79, in main
    pyopmcsp11()
  File "/usr/local/lib/python3.10/dist-packages/pyopmcsp11/core/pyopmcsp11.py", line 65, in pyopmcsp11
    opm_files(dic)
  File "/usr/local/lib/python3.10/dist-packages/pyopmcsp11/utils/writefile.py", line 132, in opm_files
    prosc = subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python'
---------------------------------------------------------------------------
And under the output directory, these files of "CSP11A.DATA  DX.INC  DZ.INC  PERMX.INC  PORO.INC  SATNUM.INC" are generated, but the TABLES.INC is absent. Do I need to compile and install the latest OPM?

**Comment by daavid00** [comment]
Hei,
If you are inside the virtual environment, then the command python is equivalent to python3. We will update the subprocess when python is called to python3 to avoid this error. One quick fix you could try is to add an alias at the end of your .bashrc (i.e., `alias python=python3`).
